name: Deploy CinemaTicketsStaging

on:
  push:
    branches: [ "staging" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render Staging
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}
